# Common system settings
common_data_dir: /opt/data
common_user_id: 1000
common_group_id: 1000
common_timezone: Australia/Melbourne

# Network settings
net_domain: sbbh.cloud
net_domain_int: int.sbbh.cloud
tailnet_domain: tailnet-7233.ts.net

# Common packages
common_packages:
  - acl
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - gnupg
  - htop
  - iperf3
  - iputils-ping
  - lsb-release
  - lsof
  - ncdu
  - net-tools
  - netcat-openbsd
  - sudo
  - tmux
  - traceroute
  - unzip
  - vim
  - zip
