---
# Service configuration

# Restic repository definitions
hetzner_storage_box_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35343732366464643838306263316231383930313232333462346134613935373539323132346637
  3764353030653561383666613434333337366132383734640a383132326332633765393230316639
  30323133643338653835373762623537613365653536386265306334343536336339326262336462
  3861616133306634320a383234303439326463663934323331303666643638663533303231386465
  38383039373465653030383365393661656431393932323661336266363063616566
hetzner_storage_box_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64373665623961323633336336306464306338633534363230663639383663366332653930646137
  6433386436333430616361623137666338386162636235630a323666316639643432363165356130
  33303735663736363862393432353938303964613164363237353363653862393965626262346263
  6235633234376561370a623336656632623466393838333436643032656461346630313339303731
  3262
restic_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34306335303236373831373132383764383431393433636234363165303130336330346436333033
  3766383436346439323466323431346332323630393334320a353737346636653265623561373964
  38663863656334653161653963663335363232663338656538343538353639343636323030376134
  6634386135346262300a373037376438643561386134666131353833393738376138656466623764
  36613333396364303239303132316562663465363261663833653166636137383530
