---
# Service configuration

# Restic repository definitions
hetzner_storage_box_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38666262616462646466316631663034623634323065363137643565643134333330313939376239
  3638313132383339663164376666666436356462623062320a343234353566356134343830373763
  64316165663533623939666235383830333933666336393166643938323038633666353231646665
  3866393733666363320a396538363462306465646364333130626466316662316630333439323163
  65373839623530643334303732396235306130613761366432666132333563636439
hetzner_storage_box_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34383632306330306535613461343937626337366464376232646435333536306436373538323132
  3563383062326430376234303032366133346463613831360a306164326337653236356366303639
  34636436393633393261646532353362383563663233313063613563353437396366656563353362
  3561313736646132370a616533626637363264383633636532343363306265363636313431323230
  3333
restic_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34306335303236373831373132383764383431393433636234363165303130336330346436333033
  3766383436346439323466323431346332323630393334320a353737346636653265623561373964
  38663863656334653161653963663335363232663338656538343538353639343636323030376134
  6634386135346262300a373037376438643561386134666131353833393738376138656466623764
  36613333396364303239303132316562663465363261663833653166636137383530
restic_repositories:
  hetzner:
    url: "sftp:{{ hetzner_storage_box_user }}@{{ hetzner_storage_box_url }}:/backups/restic"
    env:
      RESTIC_SFTP_COMMAND: "ssh {{ hetzner_storage_box_user }}@{{ hetzner_storage_box_url }} -s sftp"
  nas:
    url: "/mnt/nas/backups"
    password: "{{ restic_password }}"
