---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1 # TODO
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  staticConfigs:
    - targets:
        - nas-k8s.int.sbbh.cloud:9100
        - pve-fw.int.sbbh.cloud:9100
        - pikvm.int.sbbh.cloud:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
