---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iperf3
spec:
  chartRef:
    kind: OCIRepository
    name: iperf3
  interval: 1h
  values:
    controllers:
      iperf3:
        type: daemonset
        containers:
          server:
            image:
              repository: networkstatic/iperf3
              tag: latest@sha256:07dcca91c0e47d82d83d91de8c3d46b840eef4180499456b4fa8d6dadb46b6c8
            command: ["iperf3"]
            args: ["-s", "-p", "5201"]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
                add: ["NET_BIND_SERVICE"]
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
          client:
            image:
              repository: networkstatic/iperf3
              tag: latest@sha256:07dcca91c0e47d82d83d91de8c3d46b840eef4180499456b4fa8d6dadb46b6c8
            command: ["sleep"]
            args: ["infinity"]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 32Mi
              limits:
                cpu: 200m
                memory: 128Mi
    defaultPodOptions:
      hostNetwork: true
    service:
      server:
        ports:
          tcp:
            port: 5201
    persistence:
      tmp:
        type: emptyDir
