---
- name: Set system hostname in /etc/hostname
  ansible.builtin.copy:
    content: "{{ inventory_hostname }}\n"
    dest: /etc/hostname
    mode: '0644'
  become: true

- name: Apply hostname change
  ansible.builtin.command:
    cmd: hostname -F /etc/hostname
  become: true
  changed_when: true

- name: Update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname }}.{{ net_domain_loc }}"
    backup: true
  become: true

