---
- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  become: true

- name: Restart borgmatic timer
  ansible.builtin.systemd:
    name: borgmatic.timer
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true

