---
- name: Load container configs
  tags: [always]
  ansible.builtin.include_vars:
    dir: "{{ playbook_dir }}/../containers"
    ignore_unknown_extensions: true
    depth: 1
    name: container_configs

- name: Run container tasks
  ansible.builtin.include_tasks: wrapper.yml
  loop: "{{ containers }}"
  tags: [always]
  when: >
    'all' in ansible_run_tags or
    'containers' in ansible_run_tags or
    item in ansible_run_tags
