---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: calibre-secret
    template:
      data:
        HARDCOVER_TOKEN: "{{ .hardcover_api_key }}"
  dataFrom:
    - extract:
        key: ops/media/calibre
