---
- name: Install and configure Tailscale
  ansible.builtin.import_tasks: tailscale.yml
  when: "'tailscale' in apps or 'tailscale' in ansible_run_tags"
  tags:
    - apps
    - tailscale

- name: Install and configure Borg Backup
  ansible.builtin.import_tasks: borg.yml
  when: "'borg' in apps or 'borg' in ansible_run_tags"
  tags:
    - apps
    - borg

- name: Install Docker
  ansible.builtin.import_tasks: docker.yml
  when: "'docker' in apps or 'docker' in ansible_run_tags"
  tags:
    - apps
    - docker

- name: Install node exporter
  ansible.builtin.import_tasks: node_exporter.yml
  when: "'node_exporter' in apps or 'node_exporter' in ansible_run_tags"
  tags:
    - apps
    - node_exporter
