---
- name: Create node_exporter cert dir
  file:
    path: "/etc/node_exporter"
    state: directory
    owner: 999
    group: 997
    mode: 0600

- name: Create private key
  openssl_privatekey:
    path: /etc/node_exporter/tls.key
    size: 2048
    owner: 999
    group: 997
    mode: 0600

- name: Create certificate signing request
  openssl_csr:
    path: /etc/node_exporter/tls.csr
    privatekey_path: /etc/node_exporter/tls.key
    common_name: "{{ inventory_hostname }}"
    owner: 999
    group: 997
    mode: 0600

- name: Create self-signed certificate
  openssl_certificate:
    path: /etc/node_exporter/tls.cert
    csr_path: /etc/node_exporter/tls.csr
    privatekey_path: /etc/node_exporter/tls.key
    provider: selfsigned
    owner: 999
    group: 997
    mode: 0600

- name: Import node_exporter role
  ansible.builtin.import_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_tls_server_config:
      cert_file: /etc/node_exporter/tls.cert
      key_file: /etc/node_exporter/tls.key
