---
- Calendar:
    - Agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 5
          integrations:
            - type: sonarr
              service_group: Media
              service_name: Sonarr
            - type: radarr
              service_group: Media
              service_name: Radarr

- Infrastructure:
    - OPNsense:
        href: https://opnsense.int.sbbh.cloud:4443
        icon: opnsense.svg
        widget:
          type: opnsense
          url: https://opnsense.int.sbbh.cloud:4443
          username: "{{HOMEPAGE_VAR_OPNSENSE_KEY}}"
          password: "{{HOMEPAGE_VAR_OPNSENSE_SECRET}}"
    - Proxmox:
        icon: proxmox.svg
        href: &pve_url https://pve-fw.int.sbbh.cloud:8006
        widget:
          type: proxmox
          url: *pve_url
          username: "{{HOMEPAGE_VAR_PVE_TOKEN}}"
          password: "{{HOMEPAGE_VAR_PVE_SECRET}}"
    - Unifi:
        icon: unifi.svg
        href: &unifi_url https://unifi.int.sbbh.cloud:8443
        widget:
          type: unifi
          url: *unifi_url
          username: monitoring
          password: "{{HOMEPAGE_VAR_UNIFI_PASS}}"
