---
portainer_agent_mgmt:
  host: mgmt
  container:
    name: portainer-agent
    image: portainer/agent:2.24.0-alpine
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host:ro
    restart_policy: always
    env:
      AGENT_PORT: "9001"
      AGENT_CLUSTER_ADDR: mgmt.int.sbbh.cloud
    security_opts: []

portainer_agent_services:
  host: services
  container:
    name: portainer-agent
    image: portainer/agent:2.24.0-alpine
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host:ro
    restart_policy: always
    env:
      AGENT_PORT: "9001"
      AGENT_CLUSTER_ADDR: services.int.sbbh.cloud
    security_opts: []
