---
postgres:
  host: services
  container:
    image: postgres:14-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    ports:
      - 5432:5432
    volumes:
      - "{{ common_data_dir }}/postgres/data:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ common_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
