---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./atuin/ks.yaml
  - ./bazarr/ks.yaml
  - ./calibre/ks.yaml
  - ./homepage/ks.yaml
  - ./it-tools/ks.yaml # TODO
  - ./karakeep/ks.yaml
  - ./fusion/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./overseerr/ks.yaml
  # - ./linx/ks.yaml # TODO
  # - ./mealie/ks.yaml # TODO
  # - ./morphos/ks.yaml # TODO
  # - ./tdarr/ks.yaml # TODO
  # - ./watchstate/ks.yaml # TODO
  # - ./wizarr/ks.yaml # TODO
  # - ./jellyfin/ks.yaml # TODO
  # - ./changedetection/ks.yaml # TODO
  # - ./home-assistant/ks.yaml # TODO
