---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./bazarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  # - ./radarr/ks.yaml # TODO
  # - ./sonarr/ks.yaml # TODO
  # - ./sabnzbd/ks.yaml # TODO
  # - ./plex/ks.yaml # TODO
  # - ./home-assistant/ks.yaml # TODO
  # - ./it-tools/ks.yaml # TODO
  # - ./karakeep/ks.yaml # TODO
  # - ./audiobookshelf/ks.yaml # TODO
  # - ./calibre/ks.yaml # TODO
  # - ./homepage/ks.yaml # TODO
  # - ./iperf3/ks.yaml # TODO
  # - ./speedtest/ks.yaml # TODO
