machine:
  features:
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles: ["os:admin"]
      allowedKubernetesNamespaces: ["actions-runner-system", "system-upgrade"]
    hostDNS:
      resolveMemberNames: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    rbac: true
    stableHostname: true
  install:
    extraKernelArgs:
      - -init_on_alloc # Less security, faster puter
      - -init_on_free # Less security, faster puter
      - -selinux # Less security, faster puter
      - apparmor=0 # Less security, faster puter
      - i915.enable_guc=3 # Meteor Lake CPU / iGPU
      - init_on_alloc=0 # Less security, faster puter
      - init_on_free=0 # Less security, faster puter
      - intel_iommu=on # PCI Passthrough
      - iommu=pt # PCI Passthrough
      - iommu.passthrough=1 # Less secure, faster puter
      - mitigations=off # Less security, faster puter
      - security=none # Less security, faster puter
      - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
      - talos.auditd.disabled=1 # Less security, faster puter
  sysctls:
    fs.inotify.max_user_watches: "1048576" # Watchdog
    fs.inotify.max_user_instances: "8192" # Watchdog
    net.ipv4.tcp_fastopen: 3 # Send and accept data in the opening SYN packet
    sunrpc.tcp_slot_table_entries: 128 # NFS
    sunrpc.tcp_max_slot_table_entries: 128 # NFS
    user.max_user_namespaces: 11255 # User Namespaces
    vm.nr_hugepages: 1024 # PostgreSQL
  files:
    - op: create
      path: /etc/cri/conf.d/20-customization.part
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          device_ownership_from_security_context = true
    - op: overwrite
      path: /etc/nfsmount.conf
      permissions: 0o644
      content: |
        [ NFSMount_Global_Options ]
        nfsvers=4.2
        hard=True
        nconnect=16
        noatime=True
  kernel:
    modules:
      - name: nbd
  kubelet:
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    extraConfig:
      featureGates:
        ImageVolume: true
      serializeImagePulls: false
    image: ghcr.io/siderolabs/kubelet:v1.34.0
    nodeIP:
      validSubnets:
        - 10.11.80.0/24
    extraMounts:
      - destination: /var/mnt/extra
        type: bind
        source: /var/mnt/extra
        options: ["bind", "rshared", "rw"]
  network:
    disableSearchDomain: true
    nameservers:
      - 10.11.80.1
  udev:
    rules:
      ## Intel GPU
      - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

      ## save power
      - SUBSYSTEM=="pci", ATTR{power/control}="auto"
      - SUBSYSTEM=="ata_port", KERNEL=="ata*", ATTR{device/power/control}="auto"
      - SUBSYSTEM=="block", KERNEL=="sd[a-z]", ATTR{device/power/control}="auto"
      - SUBSYSTEM=="scsi_host", KERNEL=="host*", ATTR{link_power_management_policy}="med_power_with_dipm"
      - SUBSYSTEM=="usb", TEST=="power/control", ATTR{power/control}="auto"

      ## IO scheduler
      # BFQ is recommended for slow storage such as rotational block devices and SD cards.
      - ACTION=="add|change", SUBSYSTEM=="block", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
      - ACTION=="add|change", SUBSYSTEM=="block", KERNEL=="mmcblk?", ATTR{queue/scheduler}="bfq"

      # None is recommended for NVMe
      - ACTION=="add|change", SUBSYSTEM=="block", ATTR{queue/rotational}=="0", KERNEL=="nvme?n?", ATTR{queue/scheduler}="none"
      # Kyber is recommended for SATA SSDs.
      - ACTION=="add|change", SUBSYSTEM=="block", ATTR{queue/rotational}=="0", KERNEL=="sd?", ATTR{queue/scheduler}="kyber"
