---
- name: Purging all non-configured aliases
  oxlorg.opnsense.alias:
    multi_control:
      purge_all: true
      fail_processing: false

- name: Reloading
  oxlorg.opnsense.reload:
    target: "alias"

- name: Create aliases
  oxlorg.opnsense.alias:
    aliases: "{{ aliases }}"
