---
- name: Pulling existing config
  ansibleguy.opnsense.list:
    target: frr_bgp_general

- name: Enable FRR routing
  ansibleguy.opnsense.frr_general:
    enabled: true

- name: Configure BGP
  ansibleguy.opnsense.frr_bgp_general:
    as_number: "{{ bgp.as_number }}"
    id: "{{ bgp.router_id }}"
    reload: false

- name: Configure BGP neighbors
  ansibleguy.opnsense.frr_bgp_neighbor:
    as_number: "{{ bgp.remote_as_number }}"
    ip: "{{ hostvars[item].ip_addr | ansible.utils.ipaddr('address') }}"
    source_int: "{{ bgp.source_int }}"
    next_hop_self: true
    description: "{{ item }}"
    match_fields: ["ip", "description"]
    reload: false
  loop: "{{ bgp.neighbors }}"

- name: Reloading BGP config
  ansibleguy.opnsense.reload:
    target: frr
