---
# google oauth
google_oauth_client_id: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34323437336130383161363165633934306161633632303432303635323661316230323061656633
  3665343536343366656563613435393364613530326136300a353463303530643466336163636661
  62303562396661346136363364646262316366393030333233373965383135323166343233376431
  3162346436343634300a386263383838653736646464613234346231386537373338383662363531
  64613137323665303034333134386561303231646666326566303766663537366466303439663132
  31653064376363326630613331363531313565373965613130363439313038383032633635346132
  32663666393635613237666236356436383532626633646562316231313539376434626332633464
  33343039666364376661

# syncthing
syncthing_gui_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34333661303732626563343362626434366439363636383163326131333063643966346236383131
  3035333263396365386231363032323539396534653165360a646439393237373934363035363138
  32356536386264623730383065613664616633343336353663646139366164396232636334656432
  3461343334353639380a633034346133326538336235663536343035633833313438373463353035
  64393739636236366338663238346136303766353061393639343464356137653931
syncthing_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65633865666364623961653931316362646366323361623236373731386637393665623134643066
  6230333837646334323835306666363261343236613630380a613637343532336533623333333432
  30613837643938383133646439376139623433633430666262633532666239666363343962333932
  3963353636646332320a326437316665333166653761303937333338386439333538666563633235
  35306234623731306365393663303638343661663765663132343134316262316261303063366639
  6536373233656430313035396565356565613263636634343235

# pikvm
pikvm_admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62376430346462333930343362653462346431633136396436366230626135633965323632366264
  3232336334643164356661373463336531386637323435320a633634363836383564386431303634
  38623631646635393736323639336532353531656261656337656539393835323935396163363533
  6137343762656236360a396635663434633934393865383030333562643261613161333735666461
  30373838636436643333356162653439353464656437643563353839623238303762

# borg
borg_encryption_passphrase: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65386162633938663130613338623732343730663462386461333135326232643464336536613664
  3262333932356637383235363465383534343834653536300a646638646135666462376162336361
  65343331646161393162653366653338303537363361303336373963643232653363656530376662
  3538333565316537650a303363373432383336356537323965636663386265363563616434303436
  3165
borg_ssh_key_file: "{{ ansible_root }}/../.private/borg.key"
borgbase_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66623666396561663734343835313764656538626530613133663938333561383835363137313265
  3638663131663161336535666239363535313465303938640a373338616366646638633836316633
  61356162643463363038653639303935616236346337336434323130393532313964303165366566
  6437383333383933630a393731373338333238316465333633666335353761656338383135383131
  38376530333135343833646136386165623034306138393966346633386537356364343337383362
  38626661366336643663333037626635343838393432386261313433323037313662336635653361
  65656234653766626338643365656233383631653166373338303134323662343664316132376438
  37326332666533646233623734623461323761346631623161663561643435353761643061353139
  39626530313430613037353061636631366238333537613939306362623961343564366561376663
  65373132306539386132386432623639336432373163663437366565343962313833366166366635
  35336565383561623739653532666237306333646566346533616439353836626462646433383131
  37653733373536356330

# mongodb
mongo_initdb_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38636534393461663932623265663836363135353866336332303564393963313265333031656561
  3330353034623939333631303063666633613565366336610a326134613666353534383665393762
  62316264393566636432656464326563353563366534366235366335643233346237643666306637
  3065376634313432330a316463643766623936313763663130633463326566343437333233663764
  65396163653438396566336633333331383262643038653938626661663361306134

mongo_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36353065613837376263313363626366613865393761363430343364303238383134616534326537
  3762623666336534653266623336326536373336356136350a383134303261643166663431633662
  38363761373532326132373466353030343033633638656130393139663230313434363932643630
  6439663432336432370a373062373864633433643366666364633863316161313736623232616465
  61663032663765386466653138626336303135363138393538353363373661303065

# postgres
postgres_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30393638346536356432613632616162613561396634353530313535646266343166306465626263
  3065626336333236323261663033383536646332303037620a343730333430306364613237323637
  62383266336336353139623666643337626333323637313332663061366666326130373033306562
  6561653133633733340a353339393836376266313963666133656661643830373163393563313965
  31353765343936656336643133623134376338356537363037396366666431393638

# netbox
netbox_admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35663765613161316466623337306262646533313765393535373663373830646562353161306134
  3933363064333334656239373838393462626465616638380a633036663436663938356165303534
  64656439373161636563363839616364383331306230643738363865616664386337326230313831
  6235666632306362630a633233336431623734663632633833633235396630396531643233343634
  32633838363735366565663038663432303230383338373834663562633662396533
netbox_admin_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30356261636337623735303364366231306166643034336330356531303134616163333666633564
  6339336434366466316231316561333162663565323039340a316539373666356335336136636335
  38363034383836303262386136333631643839623837643038376461633736643730376134663661
  3235656261353261330a333763626238303062633162623966636232623834356561643434326237
  35366263393264636232356432633165333433323732646639333762633162313364386164303032
  6332386533643663316536313030343530643165613566613963
netbox_secret_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39346131353663316362343932333336363761633061333337666565623131333036633834306566
  6238383766313936343734366131353661346263383664650a313162333532336362343633343438
  65353635346439306438313266653331333463336235633862396339363839383536373239656631
  3233376330393739310a376434333635393735333639343237306465383139393564313666643664
  36613662313231653761356463663765613663366534613237653932656432353765333531613831
  61326665313661333766643561366332313663363032656361326332323436353838653133663664
  62626430363432613966326662383739626235626237396164646130396330303833653966356665
  63666635623863366638336266373937386536313464623838356262656562356233396262326666
  3233
netbox_api_token_pepper: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31376664333466613433346638626137643734653933626662316561306232336431373130366165
  6533666235333137656266643831383931623738623462370a396337393265303838333662616331
  33653336623065633362373761303633643164333162653937636463666261373735336536323536
  3536306236626432390a616337626638303063326663653364616436616337333336663639363432
  61663635326137356130356264363262616531383638646335346435326633653837666562336633
  62373138316435316161656465306138663665646132363132396561633936336138363463616264
  38643638633030386463623931663831376661373466333232643833373831626663393430376365
  31316562393733323230373734373664613334316636323332613862663636366232653164353661
  6561
netbox_db_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37346365356362333762393039643935633237616339393363376465393562356635383364393839
  3734383434393364383931353064396239303336373665640a653539646539396562633235633638
  39333432386333636263326565633734373063386335336238393965376665656232383933393131
  6137393165613633340a336261363164326138653530323134303735643934623233386633323632
  63343537303933623163336430393733383636626462666466666166386131393331
netbox_redis_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66396231373763386365316631336635616538613065653738376164626565373432363934636335
  3339613466643166616265333761346534333335636561350a653161643661343736643533663030
  35333236623863643737343730323263316632626136336330613131396235653165333566363331
  6237386137373335360a313031666361363332363535303131626636646231613035373130333732
  34626233373461333833353837383034383635383862303761333631663865356132
netbox_redis_cache_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64316430666564636232313736383535326230303965646363363365333866346463393530663736
  3637313763663538343939646366623163623238653530360a613034326135653333356263373365
  65326231373336306264626331303063306133623565653633636132643930356235333830373964
  3134333566663164360a373665353935653636663835643531396430643838636162373030386336
  66316164313164366130386362316166313864623733626565373331343734303135
