---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: NAS
    group: servers
    url: icmp://nas-k8s.int.sbbh.cloud
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: PiKVM
    group: servers
    url: icmp://pikvm.int.sbbh.cloud
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Vault
    group: servers
    url: https://vault.sbbh.cloud:8200
    interval: 60m
    conditions:
      - "[CONNECTED] == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"

metrics: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/1278086
  link: https://github.com/Subbeh
  default-sort-by: group
  buttons:
    - name: Github
      link: https://github.com/Subbeh
    - name: HomeOps
      link: https://github.com/Subbeh/home-ops

web:
  port: ${GATUS_WEB_PORT}
