---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./blackbox-exporter/ks.yaml
  # - ./fluent-bit/ks.yaml # TODO
  - ./gatus/ks.yaml
  # - ./grafana/ks.yaml # TODO
  - ./keda/ks.yaml
  # - ./kromgo/ks.yaml # TODO
  - ./kube-prometheus-stack/ks.yaml
  # - ./loki/ks.yaml # TODO
  # - ./silence-operator/ks.yaml # TODO
  # - ./smartctl-exporter/ks.yaml # TODO
  # - ./snmp-exporter/ks.yaml # TODO
