---
all:
  hosts:
    x1:
      ip_addr: 10.11.100.100/24
      mac_addr: ee:39:a3:7c:ce:25
    vps:
      ansible_user: debian
      ip_addr: 100.94.245.44/24
    pikvm:
      ansible_user: root
      ip_addr: 10.11.10.5/24
      mac_addr: dc:a6:32:73:9b:0f
    unifi-switch:
      ip_addr: 10.11.254.2/24
pve:
  hosts:
    pve-fw:
      ansible_user: root
      ip_addr: 10.11.10.100/24
    pve-nas:
      ansible_user: root
      ip_addr: 10.11.10.101/24
      cluster_network:
        ip_addr: 192.168.80.100/24
vm:
  hosts:
    opnsense:
      ip_addr: 100.87.8.30/24
    mgmt:
      ip_addr: 10.11.10.2/24
    services:
      ip_addr: 10.11.10.20/24
k8s:
  hosts:
    k8s-nuc:
      ip_addr: 10.11.10.81/24
      mac_addr: 00:00:22:50:36:46
      internal:
        ip_addr: 192.168.80.11/24
        mac_addr: 48:21:0b:55:89:ab
    k8s-opti-01:
      ip_addr: 10.11.10.82/24
      mac_addr: 54:bf:64:a1:1c:00
      internal:
        ip_addr: 192.168.80.12/24
        mac_addr: 02:26:25:02:06:43
    k8s-opti-02:
      ip_addr: 10.11.10.83/24
      mac_addr: d8:9e:f3:82:d6:59
      internal:
        ip_addr: 192.168.80.13/24
        mac_addr: 02:26:25:02:06:51
  vars:
    cluster_endpoint: k8s.int.sbbh.cloud
    cluster_endpoint_addr: 10.11.10.180
    cluster_cidr: 10.11.10.0/24
    # cluster_cidr: 10.11.80.0/24
    # vip_addr: 10.11.10.80
    # gateway_int: 10.11.80.100/24
    # gateway_root: 10.11.80.101/24
    # gateway_ext: 10.11.80.200/24
    # gateway_dns: 10.11.80.10/24
