---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: healthchecks
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: healthchecks-secret
    template:
      data:
        SECRET_KEY: "{{ .secret_key }}"
        PUSHOVER_API_TOKEN: "{{ .pushover_token }}"
        PUSHOVER_SUBSCRIPTION_URL: "{{ .hc_volsync_url }}"
  dataFrom:
    - extract:
        key: ops/k8s/healthchecks
